name: download file

on:
  #pull_request:
  workflow_dispatch:
  push:
  #  branches: 
  #    - openwrt-21.02

jobs:
  push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download file
        run: |
          mkdir download 
          wget https://github.com/cfwtf/clash_for_windows/releases/download/0.20.39/Clash.for.Windows.Setup.0.20.39.exe --no-check-certificate
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: download
          path: download
