name: download file

on:
  #pull_request:
  workflow_dispatch:
    inputs:
        url: 
          description: 'url'     
          required: false
          default: 'no'
  #push:
  #  branches: 
  #    - openwrt-21.02

jobs:
  push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: download file
        run: |
          mkdir download 
          cd download
          wget ${{github.event.inputs.url}} --no-check-certificate
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: download
          path: download
